
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-yaml
  - id: debug-statements
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/asottile/reorder_python_imports
  rev: v3.9.0
  hooks:
  - id: reorder-python-imports
    args: [--application-directories, '.:src', --py39-plus]
- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
  - id: black
    args: [--line-length=119, --target-version=py39]
- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
  - id: pyupgrade
    args: [--py37-plus]
- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.0dev
  hooks:
  - id: gitlint
- repo: https://github.com/PyCQA/bandit
  rev: 1.7.4
  hooks:
  - id: bandit
    args: ["--exclude", ".tox,.eggs,tests"]
- repo: local
  hooks:
    - id: update-inputs
      name: Update inputs
      entry: make generate-inputs
      language: system
      pass_filenames: false
- repo: https://github.com/rhysd/actionlint
  rev: v1.6.23
  hooks:
    - id: actionlint
- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
# flake8
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
    - id: flake8
      exclude: ^tests/
