name: Integration Test
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  integration-testing:
    name: Integration Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Copy in Dockerfile
        run: cp Docker/Dockerfile Dockerfile
      - name: Test action
        id: test-action
        # test with the local checkout of the action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          src_repo: andrewthetechie/gha-clone-releases
