name: Test Docker Image Build

on:
  - push

jobs:
  test-docker-image:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - { name: "gha", dockerfile: "Docker/GHA-Dockerfile" }
          - { name: "pc", dockerfile: "Docker/PC-Dockerfile" }
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3.3.0
      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # The build runs some tests on the built binary to make sure it works as part of its build
      - name: Test Build ${{ matrix.name }}
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: false
          platforms: linux/amd64,linux/arm64
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#registry-cache
          cache-from: type=gha
          cache-to: type=gha,mode=max
